# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overviewer.ui'
#
# Created: Sat Aug 27 22:51:35 2011
#      by: pyside-uic 0.2.12 running on PySide 1.0.5
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 446)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabmain = QtGui.QWidget()
        self.tabmain.setObjectName("tabmain")
        self.verticalLayout1 = QtGui.QVBoxLayout(self.tabmain)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.verticalLayout2 = QtGui.QVBoxLayout()
        self.verticalLayout2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_goRender = QtGui.QPushButton(self.tabmain)
        self.pushButton_goRender.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_goRender.sizePolicy().hasHeightForWidth())
        self.pushButton_goRender.setSizePolicy(sizePolicy)
        self.pushButton_goRender.setMinimumSize(QtCore.QSize(46, 0))
        self.pushButton_goRender.setObjectName("pushButton_goRender")
        self.horizontalLayout.addWidget(self.pushButton_goRender)
        self.verticalLayout2.addLayout(self.horizontalLayout)
        self.horizontalLayout_world = QtGui.QHBoxLayout()
        self.horizontalLayout_world.setObjectName("horizontalLayout_world")
        self.lineEdit_pathToWorld = QtGui.QLineEdit(self.tabmain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pathToWorld.sizePolicy().hasHeightForWidth())
        self.lineEdit_pathToWorld.setSizePolicy(sizePolicy)
        self.lineEdit_pathToWorld.setMinimumSize(QtCore.QSize(24, 0))
        self.lineEdit_pathToWorld.setText("")
        self.lineEdit_pathToWorld.setObjectName("lineEdit_pathToWorld")
        self.horizontalLayout_world.addWidget(self.lineEdit_pathToWorld)
        self.worldComboBox = QtGui.QComboBox(self.tabmain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.worldComboBox.sizePolicy().hasHeightForWidth())
        self.worldComboBox.setSizePolicy(sizePolicy)
        self.worldComboBox.setObjectName("worldComboBox")
        self.worldComboBox.addItem("")
        self.worldComboBox.addItem("")
        self.horizontalLayout_world.addWidget(self.worldComboBox)
        self.verticalLayout2.addLayout(self.horizontalLayout_world)
        self.lineEdit_pathToOutput = QtGui.QLineEdit(self.tabmain)
        self.lineEdit_pathToOutput.setObjectName("lineEdit_pathToOutput")
        self.verticalLayout2.addWidget(self.lineEdit_pathToOutput)
        self.progressBar = QtGui.QProgressBar(self.tabmain)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout2.addWidget(self.progressBar)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.renderModeGroupBox = QtGui.QGroupBox(self.tabmain)
        self.renderModeGroupBox.setObjectName("renderModeGroupBox")
        self.renderModeLayout = QtGui.QVBoxLayout(self.renderModeGroupBox)
        self.renderModeLayout.setObjectName("renderModeLayout")
        self.horizontalLayout_4.addWidget(self.renderModeGroupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabmain)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.numProcessors = QtGui.QSpinBox(self.groupBox_2)
        self.numProcessors.setMinimum(1)
        self.numProcessors.setObjectName("numProcessors")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.numProcessors)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout2.addLayout(self.horizontalLayout_4)
        self.verticalLayout1.addLayout(self.verticalLayout2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout1.addItem(spacerItem)
        self.tabWidget.addTab(self.tabmain, "")
        self.taboptions = QtGui.QWidget()
        self.taboptions.setObjectName("taboptions")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.taboptions)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageformat_groupBox = QtGui.QGroupBox(self.taboptions)
        self.imageformat_groupBox.setObjectName("imageformat_groupBox")
        self.png_radioButton = QtGui.QRadioButton(self.imageformat_groupBox)
        self.png_radioButton.setGeometry(QtCore.QRect(10, 15, 51, 17))
        self.png_radioButton.setChecked(True)
        self.png_radioButton.setObjectName("png_radioButton")
        self.jpeg_radioButton = QtGui.QRadioButton(self.imageformat_groupBox)
        self.jpeg_radioButton.setGeometry(QtCore.QRect(10, 40, 51, 17))
        self.jpeg_radioButton.setObjectName("jpeg_radioButton")
        self.horizontalLayout_2.addWidget(self.imageformat_groupBox)
        self.pngadvanced_groupBox = QtGui.QGroupBox(self.taboptions)
        self.pngadvanced_groupBox.setObjectName("pngadvanced_groupBox")
        self.pngcrush_radioButton = QtGui.QRadioButton(self.pngadvanced_groupBox)
        self.pngcrush_radioButton.setGeometry(QtCore.QRect(10, 40, 83, 17))
        self.pngcrush_radioButton.setObjectName("pngcrush_radioButton")
        self.pngcrushadvdef_radioButto = QtGui.QRadioButton(self.pngadvanced_groupBox)
        self.pngcrushadvdef_radioButto.setGeometry(QtCore.QRect(10, 65, 111, 17))
        self.pngcrushadvdef_radioButto.setObjectName("pngcrushadvdef_radioButto")
        self.pngcrushadvdef_agr_radioButton = QtGui.QRadioButton(self.pngadvanced_groupBox)
        self.pngcrushadvdef_agr_radioButton.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.pngcrushadvdef_agr_radioButton.setObjectName("pngcrushadvdef_agr_radioButton")
        self.none_radioButton = QtGui.QRadioButton(self.pngadvanced_groupBox)
        self.none_radioButton.setGeometry(QtCore.QRect(10, 15, 82, 17))
        self.none_radioButton.setChecked(True)
        self.none_radioButton.setObjectName("none_radioButton")
        self.horizontalLayout_2.addWidget(self.pngadvanced_groupBox)
        self.renderoptions_groupBox = QtGui.QGroupBox(self.taboptions)
        self.renderoptions_groupBox.setObjectName("renderoptions_groupBox")
        self.biome_checkBox = QtGui.QCheckBox(self.renderoptions_groupBox)
        self.biome_checkBox.setGeometry(QtCore.QRect(10, 15, 72, 17))
        self.biome_checkBox.setObjectName("biome_checkBox")
        self.forcerender_checkBox = QtGui.QCheckBox(self.renderoptions_groupBox)
        self.forcerender_checkBox.setGeometry(QtCore.QRect(10, 40, 72, 17))
        self.forcerender_checkBox.setObjectName("forcerender_checkBox")
        self.skipjs_checkBox = QtGui.QCheckBox(self.renderoptions_groupBox)
        self.skipjs_checkBox.setGeometry(QtCore.QRect(10, 65, 72, 17))
        self.skipjs_checkBox.setObjectName("skipjs_checkBox")
        self.skipsigns_checkBox = QtGui.QCheckBox(self.renderoptions_groupBox)
        self.skipsigns_checkBox.setGeometry(QtCore.QRect(10, 90, 72, 17))
        self.skipsigns_checkBox.setObjectName("skipsigns_checkBox")
        self.horizontalLayout_2.addWidget(self.renderoptions_groupBox)
        self.tabWidget.addTab(self.taboptions, "")
        self.tabhelp = QtGui.QWidget()
        self.tabhelp.setObjectName("tabhelp")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabhelp)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser = QtGui.QTextBrowser(self.tabhelp)
        self.textBrowser.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Overviewer GUI</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">This is a Qt GUI for the Overviewer script for Minecraft, which generates Google like maps of your Minecraft world.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Usage:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Just run qtov.py or qtov.exe, and it will show you main dialog where you can browse for your Minecraft world folder.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Then select the output folder where you want the files to be (HTML, JS, Tiles)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">You can tweak certain options of the render process under the \'Options\' tab.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Options:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"></p></body></html>")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.tabhelp, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_goRender, self.lineEdit_pathToOutput)
        MainWindow.setTabOrder(self.lineEdit_pathToOutput, self.worldComboBox)
        MainWindow.setTabOrder(self.worldComboBox, self.pushButton_goRender)
        MainWindow.setTabOrder(self.pushButton_goRender, self.lineEdit_pathToWorld)
        MainWindow.setTabOrder(self.lineEdit_pathToWorld, self.lineEdit_pathToOutput)
        MainWindow.setTabOrder(self.lineEdit_pathToOutput, self.tabmain)
        MainWindow.setTabOrder(self.tabmain, self.taboptions)
        MainWindow.setTabOrder(self.taboptions, self.tabhelp)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Overviewer GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_goRender.setText(QtGui.QApplication.translate("MainWindow", "Render!", None, QtGui.QApplication.UnicodeUTF8))
        self.worldComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Select a world", None, QtGui.QApplication.UnicodeUTF8))
        self.worldComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_pathToOutput.setText(QtGui.QApplication.translate("MainWindow", "/output_dir", None, QtGui.QApplication.UnicodeUTF8))
        self.renderModeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Render Modes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Other Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Processors", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabmain), QtGui.QApplication.translate("MainWindow", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.imageformat_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Image format", None, QtGui.QApplication.UnicodeUTF8))
        self.png_radioButton.setText(QtGui.QApplication.translate("MainWindow", "PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.jpeg_radioButton.setText(QtGui.QApplication.translate("MainWindow", "JPEG", None, QtGui.QApplication.UnicodeUTF8))
        self.pngadvanced_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "PNG Advanced options", None, QtGui.QApplication.UnicodeUTF8))
        self.pngcrush_radioButton.setText(QtGui.QApplication.translate("MainWindow", "pngcrush", None, QtGui.QApplication.UnicodeUTF8))
        self.pngcrushadvdef_radioButto.setText(QtGui.QApplication.translate("MainWindow", "pngcrush+advdef", None, QtGui.QApplication.UnicodeUTF8))
        self.pngcrushadvdef_agr_radioButton.setText(QtGui.QApplication.translate("MainWindow", "pngcrush+advdef\n"
"(Agressive)", None, QtGui.QApplication.UnicodeUTF8))
        self.none_radioButton.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.renderoptions_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Render options", None, QtGui.QApplication.UnicodeUTF8))
        self.biome_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Use biome", None, QtGui.QApplication.UnicodeUTF8))
        self.forcerender_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Force render", None, QtGui.QApplication.UnicodeUTF8))
        self.skipjs_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Skip JS", None, QtGui.QApplication.UnicodeUTF8))
        self.skipsigns_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Skip signs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.taboptions), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabhelp), QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

