# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overviewer.ui'
#
# Created: Sun Aug 21 22:50:25 2011
#      by: pyside-uic 0.2.9 running on PySide 1.0.3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 250)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabmain = QtGui.QWidget()
        self.tabmain.setObjectName("tabmain")
        self.verticalLayout1 = QtGui.QVBoxLayout(self.tabmain)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.verticalLayout2 = QtGui.QVBoxLayout()
        self.verticalLayout2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.worldComboBox = QtGui.QComboBox(self.tabmain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.worldComboBox.sizePolicy().hasHeightForWidth())
        self.worldComboBox.setSizePolicy(sizePolicy)
        self.worldComboBox.setObjectName("worldComboBox")
        self.worldComboBox.addItem("")
        self.worldComboBox.addItem("")
        self.horizontalLayout.addWidget(self.worldComboBox)
        self.pushButton_goRender = QtGui.QPushButton(self.tabmain)
        self.pushButton_goRender.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_goRender.sizePolicy().hasHeightForWidth())
        self.pushButton_goRender.setSizePolicy(sizePolicy)
        self.pushButton_goRender.setObjectName("pushButton_goRender")
        self.horizontalLayout.addWidget(self.pushButton_goRender)
        self.verticalLayout2.addLayout(self.horizontalLayout)
        self.lineEdit_pathToWorld = QtGui.QLineEdit(self.tabmain)
        self.lineEdit_pathToWorld.setText("")
        self.lineEdit_pathToWorld.setObjectName("lineEdit_pathToWorld")
        self.verticalLayout2.addWidget(self.lineEdit_pathToWorld)
        self.lineEdit_pathToOutput = QtGui.QLineEdit(self.tabmain)
        self.lineEdit_pathToOutput.setText("")
        self.lineEdit_pathToOutput.setObjectName("lineEdit_pathToOutput")
        self.verticalLayout2.addWidget(self.lineEdit_pathToOutput)
        self.progressBar = QtGui.QProgressBar(self.tabmain)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout2.addWidget(self.progressBar)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout2.addItem(spacerItem)
        self.verticalLayout1.addLayout(self.verticalLayout2)
        self.tabWidget.addTab(self.tabmain, "")
        self.taboptions = QtGui.QWidget()
        self.taboptions.setObjectName("taboptions")
        self.rendermodes_groupBox = QtGui.QGroupBox(self.taboptions)
        self.rendermodes_groupBox.setGeometry(QtCore.QRect(10, 10, 91, 141))
        self.rendermodes_groupBox.setFlat(False)
        self.rendermodes_groupBox.setCheckable(False)
        self.rendermodes_groupBox.setObjectName("rendermodes_groupBox")
        self.render_normal = QtGui.QCheckBox(self.rendermodes_groupBox)
        self.render_normal.setGeometry(QtCore.QRect(10, 15, 72, 20))
        self.render_normal.setChecked(True)
        self.render_normal.setObjectName("render_normal")
        self.render_lighting = QtGui.QCheckBox(self.rendermodes_groupBox)
        self.render_lighting.setGeometry(QtCore.QRect(10, 40, 72, 17))
        self.render_lighting.setObjectName("render_lighting")
        self.render_night = QtGui.QCheckBox(self.rendermodes_groupBox)
        self.render_night.setGeometry(QtCore.QRect(10, 65, 72, 17))
        self.render_night.setObjectName("render_night")
        self.render_spawn = QtGui.QCheckBox(self.rendermodes_groupBox)
        self.render_spawn.setGeometry(QtCore.QRect(10, 90, 72, 17))
        self.render_spawn.setObjectName("render_spawn")
        self.render_cave = QtGui.QCheckBox(self.rendermodes_groupBox)
        self.render_cave.setGeometry(QtCore.QRect(10, 115, 72, 17))
        self.render_cave.setObjectName("render_cave")
        self.imageformat_groupBox = QtGui.QGroupBox(self.taboptions)
        self.imageformat_groupBox.setGeometry(QtCore.QRect(130, 10, 91, 61))
        self.imageformat_groupBox.setObjectName("imageformat_groupBox")
        self.png_radioButton = QtGui.QRadioButton(self.imageformat_groupBox)
        self.png_radioButton.setGeometry(QtCore.QRect(10, 15, 51, 17))
        self.png_radioButton.setChecked(True)
        self.png_radioButton.setObjectName("png_radioButton")
        self.jpeg_radioButton = QtGui.QRadioButton(self.imageformat_groupBox)
        self.jpeg_radioButton.setGeometry(QtCore.QRect(10, 40, 51, 17))
        self.jpeg_radioButton.setObjectName("jpeg_radioButton")
        self.pngadvanced_groupBox = QtGui.QGroupBox(self.taboptions)
        self.pngadvanced_groupBox.setGeometry(QtCore.QRect(130, 80, 141, 91))
        self.pngadvanced_groupBox.setObjectName("pngadvanced_groupBox")
        self.pngcrush_radioButton = QtGui.QRadioButton(self.pngadvanced_groupBox)
        self.pngcrush_radioButton.setGeometry(QtCore.QRect(10, 15, 83, 17))
        self.pngcrush_radioButton.setObjectName("pngcrush_radioButton")
        self.pngcrushadvdef_radioButto = QtGui.QRadioButton(self.pngadvanced_groupBox)
        self.pngcrushadvdef_radioButto.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.pngcrushadvdef_radioButto.setObjectName("pngcrushadvdef_radioButto")
        self.pngcrushadvdef_agr_radioButton = QtGui.QRadioButton(self.pngadvanced_groupBox)
        self.pngcrushadvdef_agr_radioButton.setGeometry(QtCore.QRect(10, 65, 121, 17))
        self.pngcrushadvdef_agr_radioButton.setObjectName("pngcrushadvdef_agr_radioButton")
        self.processors_groupBox = QtGui.QGroupBox(self.taboptions)
        self.processors_groupBox.setGeometry(QtCore.QRect(300, 10, 71, 41))
        self.processors_groupBox.setObjectName("processors_groupBox")
        self.numProcessors = QtGui.QSpinBox(self.processors_groupBox)
        self.numProcessors.setGeometry(QtCore.QRect(10, 15, 46, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numProcessors.sizePolicy().hasHeightForWidth())
        self.numProcessors.setSizePolicy(sizePolicy)
        self.numProcessors.setMinimum(1)
        self.numProcessors.setMaximum(4)
        self.numProcessors.setObjectName("numProcessors")
        self.renderoptions_groupBox = QtGui.QGroupBox(self.taboptions)
        self.renderoptions_groupBox.setGeometry(QtCore.QRect(300, 60, 120, 121))
        self.renderoptions_groupBox.setObjectName("renderoptions_groupBox")
        self.biome_checkBox = QtGui.QCheckBox(self.renderoptions_groupBox)
        self.biome_checkBox.setGeometry(QtCore.QRect(10, 15, 72, 17))
        self.biome_checkBox.setObjectName("biome_checkBox")
        self.forcerender_checkBox = QtGui.QCheckBox(self.renderoptions_groupBox)
        self.forcerender_checkBox.setGeometry(QtCore.QRect(10, 40, 72, 17))
        self.forcerender_checkBox.setObjectName("forcerender_checkBox")
        self.skipjs_checkBox = QtGui.QCheckBox(self.renderoptions_groupBox)
        self.skipjs_checkBox.setGeometry(QtCore.QRect(10, 65, 72, 17))
        self.skipjs_checkBox.setObjectName("skipjs_checkBox")
        self.skipsigns_checkBox = QtGui.QCheckBox(self.renderoptions_groupBox)
        self.skipsigns_checkBox.setGeometry(QtCore.QRect(10, 90, 72, 17))
        self.skipsigns_checkBox.setObjectName("skipsigns_checkBox")
        self.tabWidget.addTab(self.taboptions, "")
        self.tabhelp = QtGui.QWidget()
        self.tabhelp.setObjectName("tabhelp")
        self.tabWidget.addTab(self.tabhelp, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.worldComboBox, self.pushButton_goRender)
        MainWindow.setTabOrder(self.pushButton_goRender, self.lineEdit_pathToWorld)
        MainWindow.setTabOrder(self.lineEdit_pathToWorld, self.lineEdit_pathToOutput)
        MainWindow.setTabOrder(self.lineEdit_pathToOutput, self.worldComboBox)
        MainWindow.setTabOrder(self.worldComboBox, self.pushButton_goRender)
        MainWindow.setTabOrder(self.pushButton_goRender, self.lineEdit_pathToWorld)
        MainWindow.setTabOrder(self.lineEdit_pathToWorld, self.lineEdit_pathToOutput)
        MainWindow.setTabOrder(self.lineEdit_pathToOutput, self.tabmain)
        MainWindow.setTabOrder(self.tabmain, self.taboptions)
        MainWindow.setTabOrder(self.taboptions, self.tabhelp)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Overviewer GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.worldComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Select a world", None, QtGui.QApplication.UnicodeUTF8))
        self.worldComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_goRender.setText(QtGui.QApplication.translate("MainWindow", "Render!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabmain), QtGui.QApplication.translate("MainWindow", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.rendermodes_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Render modes", None, QtGui.QApplication.UnicodeUTF8))
        self.render_normal.setText(QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.render_lighting.setText(QtGui.QApplication.translate("MainWindow", "Lighting", None, QtGui.QApplication.UnicodeUTF8))
        self.render_night.setText(QtGui.QApplication.translate("MainWindow", "Night", None, QtGui.QApplication.UnicodeUTF8))
        self.render_spawn.setText(QtGui.QApplication.translate("MainWindow", "Spawn", None, QtGui.QApplication.UnicodeUTF8))
        self.render_cave.setText(QtGui.QApplication.translate("MainWindow", "Cave", None, QtGui.QApplication.UnicodeUTF8))
        self.imageformat_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Image format", None, QtGui.QApplication.UnicodeUTF8))
        self.png_radioButton.setText(QtGui.QApplication.translate("MainWindow", "PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.jpeg_radioButton.setText(QtGui.QApplication.translate("MainWindow", "JPEG", None, QtGui.QApplication.UnicodeUTF8))
        self.pngadvanced_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "PNG Advanced options", None, QtGui.QApplication.UnicodeUTF8))
        self.pngcrush_radioButton.setText(QtGui.QApplication.translate("MainWindow", "pngcrush", None, QtGui.QApplication.UnicodeUTF8))
        self.pngcrushadvdef_radioButto.setText(QtGui.QApplication.translate("MainWindow", "pngcrush+advdef", None, QtGui.QApplication.UnicodeUTF8))
        self.pngcrushadvdef_agr_radioButton.setText(QtGui.QApplication.translate("MainWindow", "pngcrush+advdef (A)", None, QtGui.QApplication.UnicodeUTF8))
        self.processors_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Processors", None, QtGui.QApplication.UnicodeUTF8))
        self.numProcessors.setToolTip(QtGui.QApplication.translate("MainWindow", "Processors", None, QtGui.QApplication.UnicodeUTF8))
        self.renderoptions_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Render options", None, QtGui.QApplication.UnicodeUTF8))
        self.biome_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Use biome", None, QtGui.QApplication.UnicodeUTF8))
        self.forcerender_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Force render", None, QtGui.QApplication.UnicodeUTF8))
        self.skipjs_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Skip JS", None, QtGui.QApplication.UnicodeUTF8))
        self.skipsigns_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Skip signs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.taboptions), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabhelp), QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

