# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overviewer.ui'
#
# Created: Sun Aug 21 17:57:07 2011
#      by: pyside-uic 0.2.9 running on PySide 1.0.3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 250)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.worldComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.worldComboBox.sizePolicy().hasHeightForWidth())
        self.worldComboBox.setSizePolicy(sizePolicy)
        self.worldComboBox.setObjectName("worldComboBox")
        self.worldComboBox.addItem("")
        self.worldComboBox.addItem("")
        self.horizontalLayout.addWidget(self.worldComboBox)
        self.pushButton_goRender = QtGui.QPushButton(self.centralwidget)
        self.pushButton_goRender.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_goRender.sizePolicy().hasHeightForWidth())
        self.pushButton_goRender.setSizePolicy(sizePolicy)
        self.pushButton_goRender.setObjectName("pushButton_goRender")
        self.horizontalLayout.addWidget(self.pushButton_goRender)
        self.numProcessors = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numProcessors.sizePolicy().hasHeightForWidth())
        self.numProcessors.setSizePolicy(sizePolicy)
        self.numProcessors.setMinimum(1)
        self.numProcessors.setMaximum(4)
        self.numProcessors.setObjectName("numProcessors")
        self.horizontalLayout.addWidget(self.numProcessors)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lineEdit_pathToWorld = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_pathToWorld.setText("")
        self.lineEdit_pathToWorld.setObjectName("lineEdit_pathToWorld")
        self.verticalLayout.addWidget(self.lineEdit_pathToWorld)
        self.lineEdit_pathToOutput = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_pathToOutput.setObjectName("lineEdit_pathToOutput")
        self.verticalLayout.addWidget(self.lineEdit_pathToOutput)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 475, 17))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuRendermodes = QtGui.QMenu(self.menuOptions)
        self.menuRendermodes.setObjectName("menuRendermodes")
        self.menuImage_format = QtGui.QMenu(self.menuOptions)
        self.menuImage_format.setObjectName("menuImage_format")
        self.menuAdvanced_options_for_PNG = QtGui.QMenu(self.menuImage_format)
        self.menuAdvanced_options_for_PNG.setObjectName("menuAdvanced_options_for_PNG")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNormal = QtGui.QAction(MainWindow)
        self.actionNormal.setCheckable(True)
        self.actionNormal.setChecked(True)
        self.actionNormal.setObjectName("actionNormal")
        self.actionLighting = QtGui.QAction(MainWindow)
        self.actionLighting.setCheckable(True)
        self.actionLighting.setChecked(False)
        self.actionLighting.setObjectName("actionLighting")
        self.actionNight = QtGui.QAction(MainWindow)
        self.actionNight.setCheckable(True)
        self.actionNight.setChecked(False)
        self.actionNight.setObjectName("actionNight")
        self.actionSpawn = QtGui.QAction(MainWindow)
        self.actionSpawn.setCheckable(True)
        self.actionSpawn.setChecked(False)
        self.actionSpawn.setObjectName("actionSpawn")
        self.actionCave = QtGui.QAction(MainWindow)
        self.actionCave.setCheckable(True)
        self.actionCave.setChecked(False)
        self.actionCave.setObjectName("actionCave")
        self.actionForce_render = QtGui.QAction(MainWindow)
        self.actionForce_render.setCheckable(True)
        self.actionForce_render.setObjectName("actionForce_render")
        self.actionSkip_JS = QtGui.QAction(MainWindow)
        self.actionSkip_JS.setCheckable(True)
        self.actionSkip_JS.setObjectName("actionSkip_JS")
        self.actionSkip_signs = QtGui.QAction(MainWindow)
        self.actionSkip_signs.setCheckable(True)
        self.actionSkip_signs.setObjectName("actionSkip_signs")
        self.actionJPEG = QtGui.QAction(MainWindow)
        self.actionJPEG.setCheckable(True)
        self.actionJPEG.setObjectName("actionJPEG")
        self.actionPngcrush = QtGui.QAction(MainWindow)
        self.actionPngcrush.setCheckable(True)
        self.actionPngcrush.setObjectName("actionPngcrush")
        self.actionPngcrush_advdef = QtGui.QAction(MainWindow)
        self.actionPngcrush_advdef.setCheckable(True)
        self.actionPngcrush_advdef.setObjectName("actionPngcrush_advdef")
        self.actionPngcrush_advdef_agressive = QtGui.QAction(MainWindow)
        self.actionPngcrush_advdef_agressive.setCheckable(True)
        self.actionPngcrush_advdef_agressive.setObjectName("actionPngcrush_advdef_agressive")
        self.action1 = QtGui.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.actionPNG = QtGui.QAction(MainWindow)
        self.actionPNG.setCheckable(True)
        self.actionPNG.setChecked(True)
        self.actionPNG.setObjectName("actionPNG")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuRendermodes.addAction(self.actionNormal)
        self.menuRendermodes.addAction(self.actionLighting)
        self.menuRendermodes.addAction(self.actionNight)
        self.menuRendermodes.addAction(self.actionSpawn)
        self.menuRendermodes.addAction(self.actionCave)
        self.menuAdvanced_options_for_PNG.addAction(self.actionPngcrush)
        self.menuAdvanced_options_for_PNG.addAction(self.actionPngcrush_advdef)
        self.menuAdvanced_options_for_PNG.addAction(self.actionPngcrush_advdef_agressive)
        self.menuImage_format.addAction(self.actionPNG)
        self.menuImage_format.addAction(self.actionJPEG)
        self.menuImage_format.addAction(self.menuAdvanced_options_for_PNG.menuAction())
        self.menuOptions.addAction(self.menuRendermodes.menuAction())
        self.menuOptions.addAction(self.actionForce_render)
        self.menuOptions.addAction(self.actionSkip_JS)
        self.menuOptions.addAction(self.actionSkip_signs)
        self.menuOptions.addAction(self.menuImage_format.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Overviewer GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.worldComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Select a world", None, QtGui.QApplication.UnicodeUTF8))
        self.worldComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_goRender.setText(QtGui.QApplication.translate("MainWindow", "Render!", None, QtGui.QApplication.UnicodeUTF8))
        self.numProcessors.setToolTip(QtGui.QApplication.translate("MainWindow", "Processors", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_pathToOutput.setText(QtGui.QApplication.translate("MainWindow", "/Users/achin/devel/eminence-overviewer/output_dir", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRendermodes.setTitle(QtGui.QApplication.translate("MainWindow", "Render modes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImage_format.setTitle(QtGui.QApplication.translate("MainWindow", "Image format", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdvanced_options_for_PNG.setTitle(QtGui.QApplication.translate("MainWindow", "Advanced options for PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormal.setText(QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLighting.setText(QtGui.QApplication.translate("MainWindow", "Lighting", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNight.setText(QtGui.QApplication.translate("MainWindow", "Night", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpawn.setText(QtGui.QApplication.translate("MainWindow", "Spawn", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCave.setText(QtGui.QApplication.translate("MainWindow", "Cave", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForce_render.setText(QtGui.QApplication.translate("MainWindow", "Force render", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSkip_JS.setText(QtGui.QApplication.translate("MainWindow", "Skip JS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSkip_signs.setText(QtGui.QApplication.translate("MainWindow", "Skip signs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJPEG.setText(QtGui.QApplication.translate("MainWindow", "JPEG", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPngcrush.setText(QtGui.QApplication.translate("MainWindow", "pngcrush", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPngcrush_advdef.setText(QtGui.QApplication.translate("MainWindow", "pngcrush+advdef", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPngcrush_advdef_agressive.setText(QtGui.QApplication.translate("MainWindow", "pngcrush+advdef (agressive)", None, QtGui.QApplication.UnicodeUTF8))
        self.action1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPNG.setText(QtGui.QApplication.translate("MainWindow", "PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

